// <auto-generated />
using System;
using BaseConocimiento.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BaseConocimiento.Infrastructure.Migrations
{
    [DbContext(typeof(BaseConocimientoDbContext))]
    [Migration("20251229203747_InitialRefactorV2")]
    partial class InitialRefactorV2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BaseConocimiento.Domain.Entities.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoriaPadreId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_padre_id");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("color");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<bool>("EsActiva")
                        .HasColumnType("boolean")
                        .HasColumnName("es_activa");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("icono");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaPadreId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("BaseConocimiento.Domain.Entities.Consulta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConversacionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("conversacion_id");

                    b.Property<DateTime>("FechaConsulta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_consulta");

                    b.Property<bool>("FueUtil")
                        .HasColumnType("boolean")
                        .HasColumnName("fue_util");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pregunta");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("respuesta");

                    b.Property<int>("ResultadosEncontrados")
                        .HasColumnType("integer")
                        .HasColumnName("resultados_encontrados");

                    b.Property<long>("TiempoRespuestaMs")
                        .HasColumnType("bigint")
                        .HasColumnName("tiempo_respuesta_ms");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("consultas", (string)null);
                });

            modelBuilder.Entity("BaseConocimiento.Domain.Entities.ConsultaManual", b =>
                {
                    b.Property<Guid>("ConsultaId")
                        .HasColumnType("uuid")
                        .HasColumnName("consulta_id");

                    b.Property<Guid>("ManualId")
                        .HasColumnType("uuid")
                        .HasColumnName("manual_id");

                    b.Property<double>("RelevanciaPromedio")
                        .HasColumnType("double precision")
                        .HasColumnName("relevancia_promedio");

                    b.HasKey("ConsultaId", "ManualId");

                    b.HasIndex("ManualId");

                    b.ToTable("consultas_manuales", (string)null);
                });

            modelBuilder.Entity("BaseConocimiento.Domain.Entities.Manual", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_subida");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_original");

                    b.Property<int>("NumeroConsultas")
                        .HasColumnType("integer")
                        .HasColumnName("numero_consultas");

                    b.Property<long>("PesoArchivo")
                        .HasColumnType("bigint")
                        .HasColumnName("peso_archivo");

                    b.Property<string>("RutaStorage")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ruta_storage");

                    b.Property<string>("SubCategoria")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sub_categoria");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("titulo");

                    b.Property<DateTime?>("UltimaConsulta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultima_consulta");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("Estado");

                    b.HasIndex("UsuarioId");

                    b.ToTable("manuales", (string)null);
                });

            modelBuilder.Entity("BaseConocimiento.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("boolean")
                        .HasColumnName("es_activo");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nombre_completo");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.Property<int>("Rol")
                        .HasColumnType("integer")
                        .HasColumnName("rol");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("BaseConocimiento.Domain.Entities.Categoria", b =>
                {
                    b.HasOne("BaseConocimiento.Domain.Entities.Categoria", "CategoriaPadre")
                        .WithMany("SubCategorias")
                        .HasForeignKey("CategoriaPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaPadre");
                });

            modelBuilder.Entity("BaseConocimiento.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("BaseConocimiento.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ConsultasRealizadas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BaseConocimiento.Domain.Entities.ConsultaManual", b =>
                {
                    b.HasOne("BaseConocimiento.Domain.Entities.Consulta", "Consulta")
                        .WithMany("ManualesConsultados")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaseConocimiento.Domain.Entities.Manual", "Manual")
                        .WithMany("ConsultasRelacionadas")
                        .HasForeignKey("ManualId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");

                    b.Navigation("Manual");
                });

            modelBuilder.Entity("BaseConocimiento.Domain.Entities.Manual", b =>
                {
                    b.HasOne("BaseConocimiento.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Manuales")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BaseConocimiento.Domain.Entities.Usuario", "Usuario")
                        .WithMany("ManualesSubidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BaseConocimiento.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Manuales");

                    b.Navigation("SubCategorias");
                });

            modelBuilder.Entity("BaseConocimiento.Domain.Entities.Consulta", b =>
                {
                    b.Navigation("ManualesConsultados");
                });

            modelBuilder.Entity("BaseConocimiento.Domain.Entities.Manual", b =>
                {
                    b.Navigation("ConsultasRelacionadas");
                });

            modelBuilder.Entity("BaseConocimiento.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("ConsultasRealizadas");

                    b.Navigation("ManualesSubidos");
                });
#pragma warning restore 612, 618
        }
    }
}
